server:
  port: 18087
spring:
  application:
    name: user-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    registry-fetch-interval-seconds: 30 #每隔30秒从服务中心拉取列表
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10  #租约到期，服务失效时间
    lease-renewal-interval-in-seconds: 5  #租约续约间隔


    #测试推送-拉取